### ISSUE TITLE
Using  @UseGuards(AuthGuard()) get 401

### ISSUE THREAD

**Issue by gogs85** [iamolegga/nestjs-roles#194]
Hi, if I use  like this:
`  @Post("/add")
  @UseGuards(AuthGuard())
  @Roles.Params(Role.ADMIN)`
I will get 401 error Unauthorized.

How to solve the issue?

**Comment by iamolegga** [comment]
It's hard to say, it depends on your `AuthGuard` and `Roles` implementation.

Can you provide more code?

**Comment by gogs85** [comment]
I am using `AuthGuard` from "@nestjs/passport"

**Comment by iamolegga** [comment]
That's not enough, sorry, but I do not understand what is the bug here? Just check how you implement `Roles`, I mean what callback you pass to `createRolesGuard` and what it returns. Looks like your callback doesn't return `Role.ADMIN` that's why get 401.

If you still think there is a bug, then please provide more details on it

**Comment by iamolegga** [comment]
Closing due to no response
